### PR TITLE
Fix renamed issue, upgrade tooling to latest version

### PR DESCRIPTION
**Pull request by phuctm97**
- Fix renamed issue that module app won't build
- Upgrade tooling to latest Gradle, Android Studio, build tools
- Also recreate project from latest Android Studio config and run code through Android Studio recommended format

### CODE REVIEW

**Comment by michaellee8** [comment]
@phuctm97 pls revert deleted README.md

**Comment by phuctm97** [comment]
> @phuctm97 pls revert deleted README.md

Oops, reverted!

**Comment by michaellee8** [comment]
lgtm

**Review by michaellee8 — APPROVED** [review]

**Review by chaitanyapotti — COMMENTED** [review]
lgtm

**Pull request merged**
